The {pluginname} Server requires a _public_ key generated from the same _private_ key that will be used on your JSON Web Token (JWT) provider endpoint. The public key(s) stored on the {pluginname} Server are used to ensure that content is sent by authorized users.

There are two methods for generating and adding a public key to your API key:

. The secure key pair generator at {jwturl}[{accountpage} - JWT Keys] (recommended).
. Generate a key pair locally and add the _public_ key to {jwturl}[{accountpage} - JWT Keys].

== Generate a key pair using the {accountpage} JWT Keys page

The {jwturl}[{accountpage} - JWT Keys] page provides a private/public key generator, providing a quick and secure way of generating the required keys. This generator will store a copy of the _public_ key, and provide a downloadable file for both the public and private keys. {companyname} does not store the _private_ key and the key pair cannot be retrieved later.

[[generate_a_key_pair_locally]]
== Generate a key pair locally

When generating a key pair locally, use one of the supported algorithms.
include::partial$auth/jwt-supported-algorithms.adoc[]

For instructions on generating a key pair locally, see: xref:generate-rsa-key-pairs.adoc[Creating a private/public key pair for Tiny Cloud].

[[add_a_public_key_to_the_tiny_cloud_api_key]]
ifeval::[{numberedHeading} == true]
= 2. Add a public key to the {cloudname} API key
endif::[]

ifeval::[{numberedHeading} != true]
== Add a public key to the {cloudname} API key
endif::[]

Once a public key has been generated, add the public key to the {cloudname} API key at: {jwturl}[{accountpage} - JWT Keys].
